Repository Jaime-A-Perez/To-Do-List-Apple-Ecosystem, pull requests merged in 2023-11, with the labels that each got.

#1 Create CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: documentation

#2 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#4 Create and Add pull_request_template.md
  docs/pull_request_template.md
Labels: documentation

#7 🐛 Fix: Correct CODE_OF_CONDUCT.md broken link in CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: bug, documentation

#8 📝 Update README.md
  README.md
Labels: documentation

#9 Sync Develop with Main: Update with Latest Commits
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  README.md
  docs/CONTRIBUTING.md
  docs/pull_request_template.md
Labels: update

#10 🍎 Update .gitignore with additional exclusions
  .gitignore
Labels: enhancement

#11 🍎 Initialize Xcode Project
  ToDoListAppPro/ToDoListAppPro.xcodeproj/project.pbxproj
  ToDoListAppPro/ToDoListAppPro.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ToDoListAppPro/ToDoListAppPro.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ToDoListAppPro/ToDoListAppPro/Assets.xcassets/AccentColor.colorset/Contents.json
  ToDoListAppPro/ToDoListAppPro/Assets.xcassets/AppIcon.appiconset/Contents.json
  ToDoListAppPro/ToDoListAppPro/Assets.xcassets/Contents.json
  ToDoListAppPro/ToDoListAppPro/ContentView.swift
  ToDoListAppPro/ToDoListAppPro/Persistence.swift
  ToDoListAppPro/ToDoListAppPro/Preview Content/Preview Assets.xcassets/Contents.json
  ToDoListAppPro/ToDoListAppPro/ToDoListAppPro.xcdatamodeld/.xccurrentversion
  ToDoListAppPro/ToDoListAppPro/ToDoListAppPro.xcdatamodeld/ToDoListAppPro.xcdatamodel/contents
  ToDoListAppPro/ToDoListAppPro/ToDoListAppProApp.swift
  ToDoListAppPro/ToDoListAppProTests/ToDoListAppProTests.swift
  ToDoListAppPro/ToDoListAppProUITests/ToDoListAppProUITests.swift
  ToDoListAppPro/ToDoListAppProUITests/ToDoListAppProUITestsLaunchTests.swift
Labels: enhancement

#12 Implementation of the main scheme of the MVVM architecture
  ToDoListAppPro/ToDoListAppPro.xcodeproj/project.pbxproj
  ToDoListAppPro/ToDoListAppPro/Models/SingleTask.swift
  ToDoListAppPro/ToDoListAppPro/ViewModels/SingleTaskViewModel.swift
  ToDoListAppPro/ToDoListAppPro/Views/ContentView.swift
Labels: enhancement
